# Configuration for valuation models
brands:
  - mercedes
  - ford
  - fiat
  - toyota
  - tesla
  - audi
  - bmw
  - honda

model_name: ensemble

hyperparameters:
  random_state: 42

# Data settings
data:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42

# Training settings
training:
  cv_folds: 5
  save_model: true

# Ensemble settings
ensemble:
  base_models:
    - random_forest
    - gradient_boosting
    - linear_regression
  
# Optuna hyperparameter optimization (optional)
optuna:
  enabled: false
  n_trials: 100
  study_name: valuation_optimization
